
spring:
  thymeleaf:
    cache: false
  datasource:
    name: myBlog
    url: jdbc:mysql://127.0.0.1:3306/my_blog_db?&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false &serverTimezone=Asia/Shanghai
    username: root
    password: 199901
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxOpenPreparedStatements: 20
        #开启StatFilter
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
        #开启Web监控
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blogmang.entity
server:
  port: 8081
